### ISSUE TITLE
Valour.gg

### ISSUE THREAD

**Issue by lixsady** [SpikeViper/Valour#14]
Give Valour.gg more functionality like updates on release and features

**Comment by lixsady** [comment]
[](valour.gg)

**Comment by brndnln** [comment]
that post had nothing in it

**Comment by lixsady** [comment]
[](valour.gg)

**Comment by lixsady** [comment]
weird

**Comment by lixsady** [comment]
[valour.gg](url)

**Comment by lixsady** [comment]
ahh there we go

**Comment by Grimtin10** [comment]
close this

**Comment by lixsady** [comment]
it is a legit question/suggestion

**Comment by Grimtin10** [comment]
the thing is
they are gonna do that
maybe ask in the suggestions channel or q&a channel instead of here

**Comment by SpikeViper** [comment]
We will begin blocking anyone who posts anymore issues that aren't actual issues
