### ISSUE TITLE
Token system doesn't appear to account for multiple users on same computer

### ISSUE THREAD

**Issue by Grimtin10** [SpikeViper/Valour#16]
Looking over the new token system, I don't see dynamic naming of the tokens. All of the references to saving and accessing the tokens just seem to use one name "token", which doesn't seem to be able to support multiple users on the same computer/browser.

**Comment by superjacobl** [comment]
Why would you have two users in 1 broswer? You can just logout and log back in to switch accounts.

**Comment by superjacobl** [comment]
You really should only have 1 account per human.

**Comment by fruitcake5** [comment]
*does discord support multiple users on a single browser session*

**Comment by Coca16** [comment]
Why wouldn't you have 2 users? It is better the support it then not unless there is some other reasoning (also superjacob shared computers exist)

**Comment by Grimtin10** [comment]
hold on one second
yeah im closing this im dumb
(token system just overwrites token when logging in and out)

**Comment by SpikeViper** [comment]
This would be hard to change. Doing short-lived tokens would mean having to log back in every time you open the app.

**Comment by Grimtin10** [comment]
well i mean
you could dynamically name the token

**Comment by SpikeViper** [comment]
After what? The IP address? The browser ID? Names would have to be consistent and somehow identifiable per tab.

**Comment by Grimtin10** [comment]
since the token has to be secure anyways, you _could_ maybe just do "token(hash of email)" because 2 accounts cant share the same email

**Comment by fruitcake5** [comment]
> also superjacob shared computers exist

Wouldn't it be best to log out on shared devices?

**Comment by Coca16** [comment]
eh fair point

**Comment by SpikeViper** [comment]
A token being a hash of an email would be awful security since someone could get your token just by knowing your email and source code. Tokens must be random. We *could* potentially have another field added to AuthToken.cs that denotes what kind of machine the token was issued to, but that's iffy. Chrome on two different computers is still chrome. Some computers change mac addresses when rebooted. IP addresses are shared per modem.

**Comment by Grimtin10** [comment]
I said the _name_ of the token _file_, not the token itself. You have token creation done, no need to rewrite the token system, just change the naming.

**Comment by fruitcake5** [comment]
> A token being a hash of an email would be awful security since someone could get your token just by knowing your email and source code. Tokens must be random. 

He means token naming, so the name would be `TOKEN-<token here>`

> Some computers change mac addresses when rebooted. IP addresses are shared per modem.

Also CGNAT

**Comment by SpikeViper** [comment]
But then when you open Valour, how does it know which email you want to log in to? The auto-login system would be impossible.

**Comment by SpikeViper** [comment]
Unless you are suggesting we make a "user selection" screen on startup, that is.

**Comment by Grimtin10** [comment]
I would assume it just logs into the last email you logged into.
You don't actually have to do this, just a suggestion.

(User selection sounds cool tho)

**Comment by fruitcake5** [comment]
*i think this is now moving towards #suggestions territory*

**Comment by Grimtin10** [comment]
this is why i closed it

**Comment by SpikeViper** [comment]
Alright, move to the discord. This issue is now double closed.
