### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by brndnln** [SpikeViper/Valour#23]
Change the default branch to `trunk` from `master`  
The reason for this change is because slavery:
> Activists in the software community have long campaigned to replace the terms “master” and “slave” with terms that don't invoke actual human slavery. They argue that continuing to use such terms isn't inclusive, is insensitive, and highlights the tech industry's problems with diversity.
https://www.theregister.com/2020/06/15/github_replaces_master_with_main  

This issue must be assigned to Spike as he is the only person with permissions to change this.

**Comment by SpikeViper** [comment]
I personally prefer "main"

**Comment by brndnln** [comment]
main works too. I just use trunk.

**Comment by SuprSpaceBoyGamz** [comment]
Hello this is a test.

**Comment by SpikeViper** [comment]
Done
