### ISSUE TITLE
Not really an issue with code, but there was a small issue where we can't really communicate about Valour so I made this I guess?

### ISSUE THREAD

**Issue by SuprSpaceBoyGamz** [SpikeViper/Valour#24]
![favicon](https://user-images.githubusercontent.com/77362426/104383048-2fc79480-54fd-11eb-93a0-ae0739d78d7a.png)
I made a modified version of the Valour logo. Looks kinda cool I guess.

**Comment by fruitcake5** [comment]
We have a discord server - https://valour.gg/d
