### ISSUE TITLE
FAQ.md grammar and date(?)

### ISSUE THREAD

**Issue by berkkrkc09** [SpikeViper/Valour#29]
Not really an issue but...

11th line:
We plan on having a early alpha by the end of January 2020.

Should be(?):
We plan on having **_an_** early alpha by the end of January **_2021_**.

15th line:
... Even if it was encrypted Valour would have to process and proxy it which would cost money.

Should be(?):
... Even if it was encrypted, Valour would have to process and proxy it which would cost money.
----------------------------^

**Comment by fruitcake5** [comment]
Doesn't seem major, you could always make a PR and fix it

**Comment by berkkrkc09** [comment]
done
