### ISSUE TITLE
the user list is messed up

### ISSUE THREAD

**Issue by charmich0802** [SpikeViper/Valour#45]
see below happens to a lot of other people
![bug](https://user-images.githubusercontent.com/77306941/106369029-166c7800-6346-11eb-9fac-dfeaa6e6eaab.PNG)

**Comment by lixsady** [comment]
ya i see this to

**Comment by charmich0802** [comment]
this isnt fixed

**Comment by superjacobl** [comment]
Spike needs to pull my commit

**Comment by charmich0802** [comment]
> Spike needs to pull my commit

oh ok
