### ISSUE TITLE
duplicates again

### ISSUE THREAD

**Issue by drop-lt** [SpikeViper/Valour#49]
i was trying to find more bugs and this came in
![image](https://user-images.githubusercontent.com/72446297/106370005-1e6fec00-6335-11eb-9b5c-986fb8e356a1.png)

**Comment by Olirules10** [comment]
was just one window open?

**Comment by drop-lt** [comment]
one, then i refreshed the page and it persisted

**Comment by Olirules10** [comment]
oh ok, it may be fixed soon (#35) or might be a seperate issue

**Comment by drop-lt** [comment]
but then with 4 windows the original one doesnt load(i wait to someone send a message and all 3 updated)
![image](https://user-images.githubusercontent.com/72446297/106370144-19f80300-6336-11eb-9a9d-30bf289f41c6.png)

**Comment by Olirules10** [comment]
hmm
thats a seperate bug i'm pretty sure about the original window not loading, create a seperate issue

**Comment by brndnln** [comment]
This was already a known issue mentioned in #35
