### ISSUE TITLE
Valour Planet image not showing

### ISSUE THREAD

**Issue by OmegaRogue** [SpikeViper/Valour#54]
The image of the Valour planet is the alt image instead of the valour logo
![image](https://user-images.githubusercontent.com/24958536/106384837-4ad74700-63cd-11eb-8036-d8b05732dfee.png)
this is most likely due to the image url being https://valour.gg/image.png instead of the working https://valour.gg/icon-512.png that it defaults to when creating a new valour planet.

**Comment by fruitcake5** [comment]
https://valour.gg/image.png is a thing

This was like 12 hours ago
