### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by lixsady** [SpikeViper/Valour#6]
How do I get a github feed on to a discord channel

**Comment by Grimtin10** [comment]
google it

**Comment by lixsady** [comment]
I have

**Comment by lixsady** [comment]
Stupid, *slaps*

**Comment by brndnln** [comment]
https://ardalis.com/integrate-github-and-discord-with-webhooks/

**Comment by lixsady** [comment]
Dont close

**Comment by Grimtin10** [comment]
dont ask here

**Comment by brndnln** [comment]
Well please do not make issues that don't have anything to do with Valour
